/**
 * Collection of traditional Kenyan meals and modern adaptations
 * with nutritional information and budget-friendly details
 */

export const kenyanMeals = [
  {
    id: "ke-001",
    name: "Ugali na Sukuma Wiki",
    type: "dinner, lunch",
    description: "Traditional Kenyan staple of maize meal porridge served with sautéed collard greens. High in fiber and very affordable.",
    preparationTime: 10,
    cookingTime: 25,
    servings: 4,
    totalCost: 120,
    calories: 320,
    image: null,
    tags: ["Traditional", "Budget-Friendly", "Vegetarian"],
    ingredients: [
      { name: "Maize Flour", amount: "500g" },
      { name: "Sukuma Wiki (Collard Greens)", amount: "1 bunch" },
      { name: "Onion", amount: "1 medium" },
      { name: "Tomatoes", amount: "2 medium" },
      { name: "Cooking Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 320,
      protein: 8,
      carbs: 65,
      fat: 3,
      fiber: 8
    },
    region: "Nationwide"
  },
  {
    id: "ke-002",
    name: "Githeri",
    type: "lunch",
    description: "Nutritious mix of boiled maize and beans, often served with vegetables. High in protein and fiber while being economical.",
    preparationTime: 15,
    cookingTime: 90,
    servings: 6,
    totalCost: 180,
    calories: 380,
    image: null,
    tags: ["Traditional", "High Protein", "Budget-Friendly"],
    ingredients: [
      { name: "Maize (Corn)", amount: "500g" },
      { name: "Kidney Beans", amount: "500g" },
      { name: "Onion", amount: "1 large" },
      { name: "Tomatoes", amount: "3 medium" },
      { name: "Green Bell Pepper", amount: "1" },
      { name: "Garlic", amount: "2 cloves" },
      { name: "Coriander", amount: "1 handful" },
      { name: "Cooking Oil", amount: "3 tbsp" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 380,
      protein: 15,
      carbs: 70,
      fat: 4,
      fiber: 12
    },
    region: "Central Kenya"
  },
  {
    id: "ke-003",
    name: "Chapati",
    type: "dinner",
    description: "Kenyan flatbread that's crispy outside and soft inside. Perfect accompaniment for stews or can be eaten on its own.",
    preparationTime: 30,
    cookingTime: 15,
    servings: 8,
    totalCost: 150,
    calories: 210,
    image: null,
    tags: ["Bread", "Budget-Friendly", "Vegetarian"],
    ingredients: [
      { name: "Wheat Flour", amount: "500g" },
      { name: "Warm Water", amount: "300ml" },
      { name: "Salt", amount: "1 tsp" },
      { name: "Sugar", amount: "1 tsp" },
      { name: "Cooking Oil", amount: "4 tbsp" }
    ],
    nutritionFacts: {
      calories: 210,
      protein: 4,
      carbs: 30,
      fat: 7,
      fiber: 2
    },
    region: "Nationwide"
  },
  {
    id: "ke-004",
    name: "Mandazi",
    type: "breakfast",
    description: "East African doughnut-like pastry that's slightly sweet and perfect for breakfast with tea.",
    preparationTime: 15,
    cookingTime: 20,
    servings: 12,
    totalCost: 130,
    calories: 180,
    image: null,
    tags: ["Breakfast", "Sweet", "Budget-Friendly"],
    ingredients: [
      { name: "All-purpose Flour", amount: "500g" },
      { name: "Sugar", amount: "100g" },
      { name: "Coconut Milk", amount: "250ml" },
      { name: "Baking Powder", amount: "2 tsp" },
      { name: "Cardamom", amount: "1/2 tsp" },
      { name: "Cooking Oil", amount: "for frying" }
    ],
    nutritionFacts: {
      calories: 180,
      protein: 3,
      carbs: 25,
      fat: 8,
      fiber: 1
    },
    region: "Coastal Kenya"
  },
  {
    id: "ke-005",
    name: "Chai",
    type: "breakfast",
    description: "Milky and fragrant tea often spiced with cardamom, ginger, and cinnamon. An essential part of Kenyan hospitality.",
    preparationTime: 5,
    cookingTime: 10,
    servings: 4,
    totalCost: 60,
    calories: 110,
    image: null,
    tags: ["Drink", "Budget-Friendly", "Quick"],
    ingredients: [
      { name: "Milk", amount: "500ml" },
      { name: "Water", amount: "500ml" },
      { name: "Black Tea Leaves", amount: "4 tsp" },
      { name: "Sugar", amount: "to taste" },
      { name: "Cardamom", amount: "4 pods" },
      { name: "Ginger", amount: "1 small piece" },
      { name: "Cinnamon", amount: "1 small stick" }
    ],
    nutritionFacts: {
      calories: 110,
      protein: 4,
      carbs: 15,
      fat: 4,
      fiber: 0
    },
    region: "Nationwide"
  },
  {
    id: "ke-006",
    name: "Pilau Rice",
    type: "dinner",
    description: "Aromatic spiced rice often served at celebrations. This budget-friendly version delivers all the flavor without expensive meat.",
    preparationTime: 15,
    cookingTime: 35,
    servings: 6,
    totalCost: 220,
    calories: 310,
    image: null,
    tags: ["Traditional", "Spiced", "Budget-Friendly"],
    ingredients: [
      { name: "Rice", amount: "500g" },
      { name: "Onions", amount: "2 large" },
      { name: "Pilau Masala", amount: "2 tbsp" },
      { name: "Garlic", amount: "4 cloves" },
      { name: "Ginger", amount: "1 inch piece" },
      { name: "Tomato Paste", amount: "2 tbsp" },
      { name: "Cooking Oil", amount: "3 tbsp" },
      { name: "Water or Stock", amount: "1L" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 310,
      protein: 5,
      carbs: 64,
      fat: 4,
      fiber: 1
    },
    region: "Coastal Kenya"
  },
  {
    id: "ke-007",
    name: "Irio",
    type: "dinner",
    description: "Traditional Kikuyu dish of mashed potatoes, peas, corn, and greens. Nutritious and filling.",
    preparationTime: 15,
    cookingTime: 30,
    servings: 4,
    totalCost: 160,
    calories: 290,
    image: null,
    tags: ["Traditional", "Vegetarian", "Budget-Friendly"],
    ingredients: [
      { name: "Potatoes", amount: "1kg" },
      { name: "Green Peas", amount: "250g" },
      { name: "Corn Kernels", amount: "250g" },
      { name: "Spinach or Kale", amount: "1 bunch" },
      { name: "Onion", amount: "1 medium" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 290,
      protein: 8,
      carbs: 55,
      fat: 1,
      fiber: 10
    },
    region: "Central Kenya"
  },
  {
    id: "ke-008",
    name: "Mursik",
    type: "snack",
    description: "Traditional fermented milk drink from the Kalenjin community. Naturally probiotic and calcium-rich.",
    preparationTime: 10,
    cookingTime: 0,
    servings: 4,
    totalCost: 100,
    calories: 150,
    image: null,
    tags: ["Drink", "Traditional", "Probiotic"],
    ingredients: [
      { name: "Fresh Milk", amount: "1L" },
      { name: "Special Herb-treated Gourd", amount: "1" }
    ],
    nutritionFacts: {
      calories: 150,
      protein: 8,
      carbs: 12,
      fat: 8,
      fiber: 0
    },
    region: "Rift Valley"
  },
  {
    id: "ke-009",
    name: "Avocado Smoothie",
    type: "breakfast",
    description: "Creamy, nutritious smoothie featuring local Kenyan avocados. Perfect for a quick, filling breakfast.",
    preparationTime: 5,
    cookingTime: 0,
    servings: 2,
    totalCost: 120,
    calories: 280,
    image: null,
    tags: ["Healthy", "Quick", "Fruit"],
    ingredients: [
      { name: "Ripe Avocado", amount: "1 large" },
      { name: "Milk", amount: "250ml" },
      { name: "Honey", amount: "2 tbsp" },
      { name: "Banana", amount: "1 medium" },
      { name: "Ice Cubes", amount: "handful" }
    ],
    nutritionFacts: {
      calories: 280,
      protein: 6,
      carbs: 30,
      fat: 18,
      fiber: 8
    },
    region: "Modern Adaptation"
  },
  {
    id: "ke-010",
    name: "Tropical Fruit Salad",
    type: "breakfast",
    description: "Refreshing mix of locally available fruits like mango, pineapple, and papaya. Rich in vitamins and fiber.",
    preparationTime: 15,
    cookingTime: 0,
    servings: 4,
    totalCost: 200,
    calories: 120,
    image: null,
    tags: ["Healthy", "Fruit", "No-Cook"],
    ingredients: [
      { name: "Mango", amount: "1 large" },
      { name: "Pineapple", amount: "1/2 medium" },
      { name: "Papaya", amount: "1/2 medium" },
      { name: "Banana", amount: "2 medium" },
      { name: "Orange", amount: "2 medium" },
      { name: "Passion Fruit", amount: "3" },
      { name: "Honey", amount: "2 tbsp" },
      { name: "Lemon Juice", amount: "1 tbsp" }
    ],
    nutritionFacts: {
      calories: 120,
      protein: 2,
      carbs: 30,
      fat: 0,
      fiber: 5
    },
    region: "Nationwide"
  },
  {
    id: "ke-011",
    name: "Passion Fruit Juice",
    type: "snack, breakfast",
    description: "Tangy and refreshing juice made from locally grown passion fruits. Rich in vitamin C and antioxidants.",
    preparationTime: 10,
    cookingTime: 0,
    servings: 4,
    totalCost: 100,
    calories: 90,
    image: null,
    tags: ["Drink", "Healthy", "Fruit"],
    ingredients: [
      { name: "Passion Fruits", amount: "10" },
      { name: "Water", amount: "1L" },
      { name: "Sugar", amount: "to taste" },
      { name: "Ice Cubes", amount: "as needed" }
    ],
    nutritionFacts: {
      calories: 90,
      protein: 1,
      carbs: 22,
      fat: 0,
      fiber: 2
    },
    region: "Nationwide"
  },
  {
    id: "ke-012",
    name: "Matoke (Plantain Stew)",
    type: "lunch, dinner",
    description: "Hearty stew made with green plantains, often served with rice or chapati. Popular in Western Kenya.",
    preparationTime: 15,
    cookingTime: 40,
    servings: 4,
    totalCost: 200,
    calories: 310,
    image: null,
    tags: ["Traditional", "Stew", "Budget-Friendly"],
    ingredients: [
      { name: "Green Plantains", amount: "4" },
      { name: "Onions", amount: "2 medium" },
      { name: "Tomatoes", amount: "3 medium" },
      { name: "Green Bell Pepper", amount: "1" },
      { name: "Garlic", amount: "3 cloves" },
      { name: "Vegetable Oil", amount: "3 tbsp" },
      { name: "Cumin", amount: "1 tsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Water", amount: "1 cup" }
    ],
    nutritionFacts: {
      calories: 310,
      protein: 3,
      carbs: 70,
      fat: 4,
      fiber: 6
    },
    region: "Western Kenya"
  },
  {
    id: "ke-013",
    name: "Mukimo",
    type: "dinner",
    description: "Traditional Kikuyu dish of mashed potatoes, beans, corn, and greens. Nutritious and economical.",
    preparationTime: 20,
    cookingTime: 35,
    servings: 5,
    totalCost: 180,
    calories: 300,
    image: null,
    tags: ["Traditional", "Vegetarian", "Budget-Friendly"],
    ingredients: [
      { name: "Potatoes", amount: "1kg" },
      { name: "Green Peas", amount: "200g" },
      { name: "Green Maize", amount: "200g" },
      { name: "Pumpkin Leaves or Spinach", amount: "1 bunch" },
      { name: "Onion", amount: "1 medium" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 300,
      protein: 8,
      carbs: 60,
      fat: 1,
      fiber: 9
    },
    region: "Central Kenya"
  },
  {
    id: "ke-014",
    name: "Mango Avocado Salad",
    type: "lunch",
    description: "Fresh, nutritious salad combining sweet mangoes and creamy avocados. A modern take using locally available produce.",
    preparationTime: 15,
    cookingTime: 0,
    servings: 2,
    totalCost: 150,
    calories: 220,
    image: null,
    tags: ["Healthy", "Fruit", "No-Cook"],
    ingredients: [
      { name: "Ripe Mango", amount: "1 large" },
      { name: "Avocado", amount: "1 large" },
      { name: "Red Onion", amount: "1/4 cup, thinly sliced" },
      { name: "Lime Juice", amount: "2 tbsp" },
      { name: "Olive Oil", amount: "1 tbsp" },
      { name: "Cilantro", amount: "handful, chopped" },
      { name: "Salt and Pepper", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 220,
      protein: 3,
      carbs: 25,
      fat: 15,
      fiber: 9
    },
    region: "Modern Adaptation"
  },
  {
    id: "ke-015",
    name: "Uji (Porridge)",
    type: "breakfast",
    description: "Traditional Kenyan fermented porridge made from millet or sorghum flour. Nutritious and gut-friendly.",
    preparationTime: 5,
    cookingTime: 15,
    servings: 4,
    totalCost: 60,
    calories: 150,
    image: null,
    tags: ["Breakfast", "Traditional", "Budget-Friendly"],
    ingredients: [
      { name: "Millet or Sorghum Flour", amount: "200g" },
      { name: "Water", amount: "1L" },
      { name: "Sugar or Honey", amount: "to taste" },
      { name: "Lemon Juice", amount: "1 tbsp (optional)" }
    ],
    nutritionFacts: {
      calories: 150,
      protein: 4,
      carbs: 32,
      fat: 1,
      fiber: 3
    },
    region: "Nationwide"
  },
  {
    id: "ke-016",
    name: "Sukuma Wiki with Avocado",
    type: "lunch, dinner",
    description: "Simple yet nutritious meal of sautéed collard greens served with sliced avocado. High in vitamins and good fats.",
    preparationTime: 10,
    cookingTime: 15,
    servings: 2,
    totalCost: 100,
    calories: 200,
    image: null,
    tags: ["Healthy", "Quick", "Budget-Friendly", "Vegetarian"],
    ingredients: [
      { name: "Sukuma Wiki (Collard Greens)", amount: "1 bunch" },
      { name: "Avocado", amount: "1 large" },
      { name: "Onion", amount: "1 small" },
      { name: "Tomato", amount: "1 medium" },
      { name: "Cooking Oil", amount: "1 tbsp" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 200,
      protein: 5,
      carbs: 15,
      fat: 16,
      fiber: 10
    },
    region: "Modern Adaptation"
  },
  {
    id: "ke-017",
    name: "Nyama Choma",
    type: "dinner",
    description: "Traditional Kenyan grilled meat, typically goat or beef, marinated with simple spices and slow-cooked over an open flame for a smoky flavor.",
    preparationTime: 30,
    cookingTime: 60,
    servings: 4,
    totalCost: 800,
    calories: 450,
    image: null,
    tags: ["Traditional", "Protein", "Special Occasion"],
    ingredients: [
      { name: "Goat or Beef Meat", amount: "1 kg" },
      { name: "Salt", amount: "2 tsp" },
      { name: "Black Pepper", amount: "1 tsp" },
      { name: "Garlic", amount: "4 cloves, crushed" },
      { name: "Lemon", amount: "1, juiced" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Kachumbari Salad", amount: "to serve" }
    ],
    nutritionFacts: {
      calories: 450,
      protein: 48,
      carbs: 2,
      fat: 25,
      fiber: 0
    },
    region: "Nationwide",
    instructions: [
      "Mix salt, black pepper, crushed garlic, lemon juice, and oil to make a marinade.",
      "Cut meat into large chunks and coat with the marinade. Let it rest for at least 30 minutes.",
      "Preheat grill or open fire to medium-high heat.",
      "Grill meat for about 45-60 minutes, turning occasionally, until well cooked and slightly charred.",
      "Let meat rest for 10 minutes before cutting into smaller pieces.",
      "Serve hot with kachumbari salad and ugali."
    ],
    pdfUrl: "https://example.com/recipes/nyama-choma.pdf",
    videoUrl: "https://www.youtube.com/embed/example"
  },
  {
    id: "ke-018",
    name: "Kachumbari",
    type: "snack",
    description: "Fresh and tangy Kenyan salad made with tomatoes, onions, and cilantro. It's the perfect accompaniment to grilled meats and other main dishes.",
    preparationTime: 10,
    cookingTime: 0,
    servings: 4,
    totalCost: 100,
    calories: 60,
    image: null,
    tags: ["Salad", "Quick", "No-Cook", "Vegetarian"],
    ingredients: [
      { name: "Tomatoes", amount: "3 medium, diced" },
      { name: "Red Onion", amount: "1 medium, finely sliced" },
      { name: "Cilantro/Coriander", amount: "1/4 cup, chopped" },
      { name: "Green Chili", amount: "1 small, finely chopped (optional)" },
      { name: "Lemon or Lime Juice", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 60,
      protein: 2,
      carbs: 13,
      fat: 0,
      fiber: 3
    },
    region: "Nationwide",
    instructions: [
      "Soak sliced onions in cold water for 5-10 minutes to reduce sharpness, then drain well.",
      "In a bowl, combine diced tomatoes and sliced onions.",
      "Add chopped cilantro and green chili (if using).",
      "Drizzle with lemon or lime juice.",
      "Season with salt and toss gently to combine.",
      "Let the salad sit for about 5 minutes to allow flavors to meld before serving."
    ]
  },
  {
    id: "ke-019",
    name: "Samosas",
    type: "snack, breakfast",
    description: "Popular Kenyan street food with Indian influence - crispy triangular pastries filled with seasoned minced meat or vegetables.",
    preparationTime: 45,
    cookingTime: 20,
    servings: 12,
    totalCost: 350,
    calories: 180,
    image: null,
    tags: ["Snack", "Street Food", "Indian Influence"],
    ingredients: [
      { name: "All-purpose Flour", amount: "2 cups" },
      { name: "Salt", amount: "1 tsp" },
      { name: "Vegetable Oil", amount: "6 tbsp + for frying" },
      { name: "Water", amount: "6-7 tbsp" },
      { name: "Minced Beef or Lamb", amount: "500g" },
      { name: "Onion", amount: "1 large, finely chopped" },
      { name: "Garlic", amount: "3 cloves, minced" },
      { name: "Ginger", amount: "1 tbsp, grated" },
      { name: "Ground Cumin", amount: "1 tsp" },
      { name: "Ground Coriander", amount: "1 tsp" },
      { name: "Garam Masala", amount: "1/2 tsp" },
      { name: "Green Peas", amount: "1/2 cup" },
      { name: "Cilantro/Coriander", amount: "1/4 cup, chopped" }
    ],
    nutritionFacts: {
      calories: 180,
      protein: 8,
      carbs: 15,
      fat: 10,
      fiber: 1
    },
    region: "Urban Kenya",
    instructions: [
      "For the dough: Mix flour and salt in a bowl. Add oil and rub until mixture resembles breadcrumbs. Add water gradually and knead to form a stiff dough. Cover and rest for 30 minutes.",
      "For the filling: Heat oil in a pan, add onions and sauté until golden. Add garlic and ginger, cook for 1 minute.",
      "Add minced meat and brown it. Add all spices and salt, cook until fragrant.",
      "Add green peas and cook until meat is fully cooked. Mix in chopped cilantro and let the filling cool.",
      "Divide dough into 6 equal parts. Roll each into a circle and cut in half.",
      "Form each half into a cone, fill with the meat mixture, seal the edges with water.",
      "Deep fry the samosas in hot oil until golden brown and crispy.",
      "Drain on paper towels and serve hot with ketchup or chutney."
    ]
  },
  {
    id: "ke-020",
    name: "Maharagwe (Bean Stew)",
    type: "lunch",
    description: "Hearty Kenyan red kidney bean stew cooked with coconut milk and spices. A protein-rich, budget-friendly meal perfect for everyday dining.",
    preparationTime: 15,
    cookingTime: 60,
    servings: 6,
    totalCost: 220,
    calories: 310,
    image: null,
    tags: ["Stew", "Budget-Friendly", "Vegetarian", "High Protein"],
    ingredients: [
      { name: "Red Kidney Beans", amount: "500g, soaked overnight" },
      { name: "Coconut Milk", amount: "400ml" },
      { name: "Tomatoes", amount: "3 medium, chopped" },
      { name: "Onion", amount: "1 large, chopped" },
      { name: "Garlic", amount: "3 cloves, minced" },
      { name: "Green Chilies", amount: "1-2, chopped (optional)" },
      { name: "Ground Cumin", amount: "1 tsp" },
      { name: "Ground Coriander", amount: "1 tsp" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Fresh Cilantro/Coriander", amount: "handful, chopped" }
    ],
    nutritionFacts: {
      calories: 310,
      protein: 16,
      carbs: 42,
      fat: 10,
      fiber: 12
    },
    region: "Coastal Kenya",
    instructions: [
      "Drain and rinse the soaked beans, then place in a pot with enough fresh water to cover. Bring to a boil and cook until beans are tender, about 40-50 minutes.",
      "In a separate pan, heat oil and sauté onions until golden brown.",
      "Add garlic and green chilies, sauté for 1 minute until fragrant.",
      "Add chopped tomatoes and cook until soft and oil begins to separate.",
      "Add ground cumin and coriander, stir well.",
      "Add the cooked beans with some of their cooking liquid, coconut milk, and salt.",
      "Simmer on low heat for 15-20 minutes until the stew thickens.",
      "Garnish with fresh cilantro and serve hot with rice, chapati, or ugali."
    ]
  },
  {
    id: "ke-021",
    name: "Chipo (Kenyan Potato Fritters)",
    type: "snack",
    description: "Crispy on the outside, soft on the inside - these spiced potato fritters are a popular street food in Kenyan coastal regions.",
    preparationTime: 20,
    cookingTime: 15,
    servings: 4,
    totalCost: 150,
    calories: 270,
    image: null,
    tags: ["Street Food", "Coastal", "Snack", "Vegetarian"],
    ingredients: [
      { name: "Large Potatoes", amount: "4, peeled and cut into 1/2 inch slices" },
      { name: "Gram Flour (Chickpea Flour)", amount: "1 cup" },
      { name: "Turmeric Powder", amount: "1/2 tsp" },
      { name: "Red Chili Powder", amount: "1/2 tsp" },
      { name: "Garlic Paste", amount: "1 tsp" },
      { name: "Ginger Paste", amount: "1 tsp" },
      { name: "Lemon Juice", amount: "1 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Water", amount: "as needed" },
      { name: "Vegetable Oil", amount: "for deep frying" },
      { name: "Fresh Cilantro/Coriander", amount: "2 tbsp, finely chopped" }
    ],
    nutritionFacts: {
      calories: 270,
      protein: 7,
      carbs: 40,
      fat: 9,
      fiber: 5
    },
    region: "Coastal Kenya",
    instructions: [
      "Parboil potato slices until slightly soft but still firm, about 5-7 minutes. Drain and set aside.",
      "In a bowl, make a thick batter by mixing gram flour, turmeric, chili powder, garlic paste, ginger paste, lemon juice, salt, and water.",
      "Add chopped cilantro to the batter and mix well.",
      "Heat oil in a deep pan for frying.",
      "Dip each potato slice in the batter, coating completely.",
      "Carefully drop coated potato slices into hot oil and fry until golden brown and crispy.",
      "Remove with a slotted spoon and drain on paper towels.",
      "Serve hot with tamarind chutney or ketchup."
    ]
  },
  {
    id: "ke-022",
    name: "Mahamri (Coconut Donuts)",
    type: "breakfast",
    description: "Sweet, triangular-shaped deep-fried pastries flavored with cardamom and coconut milk. A breakfast favorite along the Kenyan coast.",
    preparationTime: 120,
    cookingTime: 20,
    servings: 16,
    totalCost: 200,
    calories: 160,
    image: null,
    tags: ["Breakfast", "Sweet", "Coastal", "Snack"],
    ingredients: [
      { name: "All-purpose Flour", amount: "4 cups" },
      { name: "Yeast", amount: "1 tbsp" },
      { name: "Sugar", amount: "1/2 cup" },
      { name: "Cardamom Powder", amount: "1 tsp" },
      { name: "Coconut Milk", amount: "1 cup, warm" },
      { name: "Water", amount: "1/4 cup, warm" },
      { name: "Vegetable Oil", amount: "for deep frying" }
    ],
    nutritionFacts: {
      calories: 160,
      protein: 2,
      carbs: 25,
      fat: 6,
      fiber: 1
    },
    region: "Coastal Kenya",
    instructions: [
      "In a large bowl, mix flour, sugar, cardamom powder, and yeast.",
      "Add warm coconut milk and water, mix to form a soft dough.",
      "Knead the dough for about 10 minutes until smooth and elastic.",
      "Cover with a damp cloth and let it rise in a warm place for 1-2 hours until doubled in size.",
      "Punch down the dough and divide into 8 equal balls.",
      "Roll each ball into a circle about 1/4 inch thick, then cut into quarters to form triangles.",
      "Let the triangles rest for 20 minutes.",
      "Heat oil in a deep pan. When hot, carefully drop the triangles in and fry until golden brown on both sides.",
      "Drain on paper towels and serve warm with Kenyan chai."
    ]
  },
  {
    id: "ke-023",
    name: "Tilapia with Ugali",
    type: "dinner",
    description: "Fresh tilapia fish fried to perfection, served with traditional ugali and sukuma wiki. A staple meal from the Lake Victoria region.",
    preparationTime: 20,
    cookingTime: 40,
    servings: 4,
    totalCost: 700,
    calories: 550,
    image: null,
    tags: ["Traditional", "Fish", "Lake Region", "Protein"],
    ingredients: [
      { name: "Whole Tilapia Fish", amount: "4, cleaned" },
      { name: "Lemon", amount: "1, juiced" },
      { name: "Garlic", amount: "4 cloves, crushed" },
      { name: "Salt", amount: "to taste" },
      { name: "Ground Black Pepper", amount: "1/2 tsp" },
      { name: "Vegetable Oil", amount: "for frying" },
      { name: "Maize Flour (for ugali)", amount: "500g" },
      { name: "Water (for ugali)", amount: "1L" },
      { name: "Sukuma Wiki (collard greens)", amount: "1 bunch" },
      { name: "Onion", amount: "1, chopped" },
      { name: "Tomatoes", amount: "2, chopped" }
    ],
    nutritionFacts: {
      calories: 550,
      protein: 45,
      carbs: 55,
      fat: 15,
      fiber: 4
    },
    region: "Lake Victoria Region",
    instructions: [
      "For the fish: Make deep cuts on both sides of each fish. Mix lemon juice, crushed garlic, salt, and pepper and rub the mixture all over the fish, including inside the cuts. Let marinate for 15 minutes.",
      "Heat oil in a large pan and fry the fish until crispy and golden on both sides, about 7-10 minutes per side.",
      "For the ugali: Bring water to a boil in a pot. Gradually add maize flour while stirring continuously to avoid lumps.",
      "Keep stirring until the mixture becomes thick and pulls away from the sides of the pot. Cover and let cook on low heat for 5 minutes.",
      "For sukuma wiki: In a separate pan, sauté onions until translucent. Add chopped tomatoes and cook until soft.",
      "Add chopped collard greens, salt, and a little water if needed. Cover and cook until greens are tender.",
      "Serve the fried fish with ugali and sukuma wiki on the side."
    ]
  },
  {
    id: "ke-024",
    name: "Bhajia (Potato Fritters)",
    type: "snack, lunch",
    description: "Kenyan-style potato fritters with Indian influence, made with thinly sliced potatoes in a spiced gram flour batter. A popular street food.",
    preparationTime: 15,
    cookingTime: 15,
    servings: 4,
    totalCost: 150,
    calories: 280,
    image: null,
    tags: ["Snack", "Street Food", "Indian Influence", "Vegetarian"],
    ingredients: [
      { name: "Potatoes", amount: "4 large, thinly sliced" },
      { name: "Gram Flour (Besan)", amount: "1 cup" },
      { name: "Water", amount: "1/2 cup" },
      { name: "Salt", amount: "1 tsp" },
      { name: "Chili Powder", amount: "1/2 tsp" },
      { name: "Turmeric Powder", amount: "1/4 tsp" },
      { name: "Cumin Powder", amount: "1/2 tsp" },
      { name: "Fresh Cilantro", amount: "2 tbsp, chopped" },
      { name: "Green Chili", amount: "1, finely chopped" },
      { name: "Vegetable Oil", amount: "for deep frying" }
    ],
    nutritionFacts: {
      calories: 280,
      protein: 5,
      carbs: 38,
      fat: 12,
      fiber: 4
    },
    region: "Urban Kenya",
    instructions: [
      "In a bowl, mix gram flour with all the spices, salt, and chopped cilantro.",
      "Gradually add water to make a thick batter that can coat the back of a spoon.",
      "Wash and peel the potatoes. Slice them thinly, ideally using a mandoline.",
      "Heat oil in a deep pan for frying.",
      "Dip each potato slice in the batter, ensuring it's well coated.",
      "Carefully slide the coated slices into hot oil and fry until golden brown and crispy.",
      "Remove with a slotted spoon and drain on paper towels to remove excess oil.",
      "Serve hot with ketchup or tamarind chutney."
    ]
  },
  {
    id: "ke-025",
    name: "Mutura (Kenyan Sausage)",
    type: "snack",
    description: "Traditional Kenyan sausage made from a mixture of meat, offal, and blood, stuffed into intestine casings and grilled. A popular street food with a unique smoky flavor.",
    preparationTime: 40,
    cookingTime: 30,
    servings: 6,
    totalCost: 400,
    calories: 320,
    image: null,
    tags: ["Street Food", "Traditional", "Meat", "Protein"],
    ingredients: [
      { name: "Goat or Beef Intestines", amount: "for casings" },
      { name: "Goat or Beef Meat", amount: "500g, chopped" },
      { name: "Goat or Beef Blood", amount: "1 cup (optional)" },
      { name: "Onions", amount: "2 large, finely chopped" },
      { name: "Green Chili", amount: "2, finely chopped" },
      { name: "Garlic", amount: "4 cloves, minced" },
      { name: "Fresh Ginger", amount: "1 inch, grated" },
      { name: "Salt", amount: "to taste" },
      { name: "Black Pepper", amount: "1 tsp" },
      { name: "Coriander Powder", amount: "1 tsp" },
      { name: "Cumin Powder", amount: "1/2 tsp" }
    ],
    nutritionFacts: {
      calories: 320,
      protein: 22,
      carbs: 8,
      fat: 23,
      fiber: 1
    },
    region: "Central Kenya",
    instructions: [
      "Clean the intestines thoroughly by turning them inside out, washing with salt and water, then soaking in lemon water.",
      "In a large bowl, mix the chopped meat with all the spices, onions, chili, garlic, and ginger.",
      "If using blood, mix it with the meat mixture.",
      "Stuff the mixture into the cleaned intestines and tie off at intervals to form sausages.",
      "Bring a pot of water to boil and simmer the sausages for about 20 minutes.",
      "Remove the sausages and allow to dry slightly.",
      "Grill the sausages over an open flame until charred and crispy on the outside.",
      "Cut into pieces and serve hot with kachumbari salad."
    ]
  },
  {
    id: "ke-026",
    name: "Kunde (Black-eyed Peas Stew)",
    type: "lunch, dinner",
    description: "Nutritious stew made with black-eyed peas, often cooked with tomatoes and onions. A protein-rich vegetarian dish popular in rural Kenya.",
    preparationTime: 15,
    cookingTime: 50,
    servings: 6,
    totalCost: 180,
    calories: 260,
    image: null,
    tags: ["Vegetarian", "Stew", "High Protein", "Budget-Friendly"],
    ingredients: [
      { name: "Black-eyed Peas", amount: "500g, soaked overnight" },
      { name: "Onion", amount: "1 large, chopped" },
      { name: "Tomatoes", amount: "3 medium, chopped" },
      { name: "Garlic", amount: "3 cloves, minced" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Fresh Cilantro", amount: "handful, chopped" },
      { name: "Water", amount: "as needed" }
    ],
    nutritionFacts: {
      calories: 260,
      protein: 17,
      carbs: 45,
      fat: 2,
      fiber: 11
    },
    region: "Western Kenya",
    instructions: [
      "Drain the soaked black-eyed peas and rinse well.",
      "In a pot, heat oil and sauté onions until translucent.",
      "Add garlic and sauté for another minute.",
      "Add chopped tomatoes and cook until soft.",
      "Add the black-eyed peas and enough water to cover them.",
      "Bring to a boil, then reduce heat, cover, and simmer for about 45 minutes or until peas are tender.",
      "Add salt to taste and garnish with chopped cilantro before serving.",
      "Serve hot with ugali, rice, or chapati."
    ]
  },
  {
    id: "ke-027",
    name: "Mbaazi wa Nazi (Pigeon Peas in Coconut Milk)",
    type: "lunch",
    description: "A flavorful coastal Kenyan dish made with pigeon peas slow-cooked in coconut milk. Often served for lunch with rice or chapati.",
    preparationTime: 20,
    cookingTime: 60,
    servings: 6,
    totalCost: 220,
    calories: 300,
    image: null,
    tags: ["Traditional", "Coastal", "Vegetarian", "Budget-Friendly"],
    ingredients: [
      { name: "Pigeon Peas", amount: "500g, dried and soaked overnight" },
      { name: "Coconut Milk", amount: "500ml" },
      { name: "Onion", amount: "1 large, finely chopped" },
      { name: "Garlic", amount: "4 cloves, minced" },
      { name: "Tomato", amount: "1 large, chopped" },
      { name: "Green Chili", amount: "1, slit lengthwise (optional)" },
      { name: "Cumin Seeds", amount: "1 tsp" },
      { name: "Ground Turmeric", amount: "1/2 tsp" },
      { name: "Ground Coriander", amount: "1 tsp" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Fresh Cilantro", amount: "handful, chopped" }
    ],
    nutritionFacts: {
      calories: 300,
      protein: 16,
      carbs: 40,
      fat: 12,
      fiber: 14
    },
    region: "Coastal Kenya",
    instructions: [
      "Rinse the soaked pigeon peas and cook them in plenty of water until tender, about 40-45 minutes. Drain and set aside.",
      "In a large pot, heat oil and add cumin seeds. Let them splutter.",
      "Add chopped onions and sauté until golden brown.",
      "Add minced garlic and green chili, cook for another minute.",
      "Add chopped tomato, turmeric, and coriander powder. Cook until tomatoes are soft and oil separates.",
      "Add the cooked pigeon peas and salt, stir well.",
      "Pour in coconut milk, mix thoroughly, and bring to a simmer.",
      "Cover and cook on low heat for 15-20 minutes, stirring occasionally to prevent sticking.",
      "Garnish with fresh cilantro and serve hot with rice, chapati, or cassava."
    ]
  },
  {
    id: "ke-028",
    name: "Matumbo (Tripe Stew)",
    type: "dinner",
    description: "A hearty traditional Kenyan stew made from beef tripe, slow-cooked with aromatic spices and vegetables. A favorite at local eateries.",
    preparationTime: 30,
    cookingTime: 120,
    servings: 6,
    totalCost: 450,
    calories: 380,
    image: null,
    tags: ["Traditional", "Meat", "Budget-Friendly", "Stew"],
    ingredients: [
      { name: "Beef Tripe", amount: "1kg, thoroughly cleaned" },
      { name: "Onions", amount: "2 large, chopped" },
      { name: "Tomatoes", amount: "4 medium, chopped" },
      { name: "Garlic", amount: "6 cloves, minced" },
      { name: "Ginger", amount: "2 tbsp, grated" },
      { name: "Green Bell Pepper", amount: "1, chopped" },
      { name: "Vegetable Oil", amount: "3 tbsp" },
      { name: "Cumin Powder", amount: "1 tsp" },
      { name: "Coriander Powder", amount: "1 tsp" },
      { name: "Turmeric Powder", amount: "1/2 tsp" },
      { name: "Black Pepper", amount: "1/2 tsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Fresh Cilantro", amount: "handful, chopped" },
      { name: "Water", amount: "as needed" }
    ],
    nutritionFacts: {
      calories: 380,
      protein: 32,
      carbs: 12,
      fat: 24,
      fiber: 3
    },
    region: "Nationwide",
    instructions: [
      "Cut cleaned tripe into bite-sized pieces and place in a large pot with enough water to cover.",
      "Bring to a boil and simmer on medium heat for about 60-90 minutes until tender. Drain and set aside.",
      "In a large pan, heat oil and sauté onions until translucent.",
      "Add garlic and ginger, cook for 1-2 minutes until fragrant.",
      "Add all the spices and stir for 30 seconds.",
      "Add chopped tomatoes and bell pepper, cook until tomatoes break down.",
      "Add the cooked tripe and mix well with the sauce.",
      "Add enough water to create a stew-like consistency.",
      "Cover and simmer on low heat for 30 minutes, stirring occasionally.",
      "Season with salt to taste and garnish with fresh cilantro.",
      "Serve hot with ugali, chapati, or rice."
    ]
  },
  {
    id: "ke-029",
    name: "Omena (Silver Cyprinid) with Kale",
    type: "lunch, dinner",
    description: "Small dried fish from Lake Victoria cooked with kale to create a nutrient-dense, affordable meal that's popular in Western Kenya.",
    preparationTime: 20,
    cookingTime: 30,
    servings: 4,
    totalCost: 180,
    calories: 290,
    image: null,
    tags: ["Traditional", "Fish", "Budget-Friendly", "High Protein", "Lake Region"],
    ingredients: [
      { name: "Omena (Dried Small Fish)", amount: "250g" },
      { name: "Kale or Sukuma Wiki", amount: "1 large bunch, chopped" },
      { name: "Onion", amount: "1 large, chopped" },
      { name: "Tomatoes", amount: "2 medium, chopped" },
      { name: "Garlic", amount: "2 cloves, minced" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Water", amount: "1/2 cup" }
    ],
    nutritionFacts: {
      calories: 290,
      protein: 38,
      carbs: 14,
      fat: 12,
      fiber: 5
    },
    region: "Lake Victoria Region",
    instructions: [
      "Rinse the dried omena thoroughly to remove dust and debris.",
      "Soak the omena in warm water for about 5-10 minutes, then drain well.",
      "Heat oil in a large pan and sauté onions until translucent.",
      "Add minced garlic and stir for 30 seconds until fragrant.",
      "Add chopped tomatoes and cook until soft and slightly saucy.",
      "Add the cleaned omena and stir to combine with the tomato mixture.",
      "Add a little water, cover, and simmer for about 10 minutes.",
      "Add the chopped kale, salt, and mix well.",
      "Cover and cook for another 5-7 minutes until kale is tender but still bright green.",
      "Serve hot with ugali or rice."
    ]
  },
  {
    id: "ke-030",
    name: "Nduma na Nyama (Arrowroot with Meat)",
    type: "dinner",
    description: "Tender pieces of arrowroot cooked with meat in a flavorful stew. A hearty and satisfying dish popular in Central Kenya.",
    preparationTime: 25,
    cookingTime: 60,
    servings: 4,
    totalCost: 400,
    calories: 420,
    image: null,
    tags: ["Traditional", "Meat", "Central Region", "Stew"],
    ingredients: [
      { name: "Arrowroot", amount: "4 medium, peeled and cut into chunks" },
      { name: "Beef or Goat Meat", amount: "500g, cubed" },
      { name: "Onion", amount: "1 large, chopped" },
      { name: "Tomatoes", amount: "3 medium, chopped" },
      { name: "Garlic", amount: "3 cloves, minced" },
      { name: "Ginger", amount: "1 tbsp, grated" },
      { name: "Green Bell Pepper", amount: "1, chopped" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Black Pepper", amount: "1/2 tsp" },
      { name: "Fresh Cilantro", amount: "handful, chopped" },
      { name: "Water", amount: "2 cups" }
    ],
    nutritionFacts: {
      calories: 420,
      protein: 28,
      carbs: 45,
      fat: 15,
      fiber: 6
    },
    region: "Central Kenya",
    instructions: [
      "In a large pot, heat oil and brown the meat cubes on all sides.",
      "Add chopped onions and sauté until translucent.",
      "Add garlic and ginger, cook for another minute until fragrant.",
      "Add chopped tomatoes and bell pepper, cook until tomatoes are soft.",
      "Season with salt and black pepper.",
      "Add water, cover, and simmer for about 30 minutes until meat is almost tender.",
      "Add the arrowroot chunks and continue cooking for another 20-25 minutes until both meat and arrowroot are tender.",
      "If needed, add a little more water during cooking to maintain a stew-like consistency.",
      "Garnish with fresh cilantro before serving.",
      "Serve hot as a complete meal or with a side of vegetables."
    ]
  },
  {
    id: "ke-031",
    name: "Wimbi Porridge (Finger Millet Porridge)",
    type: "breakfast",
    description: "Nutritious finger millet porridge, often fermented for a tangy flavor. Rich in iron and calcium, it's a traditional Kenyan energy breakfast.",
    preparationTime: 5,
    cookingTime: 15,
    servings: 4,
    totalCost: 70,
    calories: 180,
    image: null,
    tags: ["Traditional", "Breakfast", "Vegetarian", "Budget-Friendly", "Healthy"],
    ingredients: [
      { name: "Finger Millet Flour", amount: "1 cup" },
      { name: "Cold Water", amount: "1 cup" },
      { name: "Boiling Water", amount: "4 cups" },
      { name: "Sugar or Honey", amount: "to taste" },
      { name: "Lemon Juice", amount: "1 tbsp (optional)" },
      { name: "Milk", amount: "to serve (optional)" }
    ],
    nutritionFacts: {
      calories: 180,
      protein: 5,
      carbs: 35,
      fat: 1,
      fiber: 4
    },
    region: "Nationwide",
    instructions: [
      "Mix the finger millet flour with cold water to form a smooth paste without lumps.",
      "Bring 4 cups of water to a boil in a large pot.",
      "Gradually add the millet paste to the boiling water, stirring continuously to prevent lumps.",
      "Reduce heat to low and simmer for about 10-15 minutes, stirring occasionally.",
      "The porridge should thicken and become smooth. Add more water if it gets too thick.",
      "Add sugar or honey to taste and stir well.",
      "For a tangy flavor, add a tablespoon of lemon juice (optional).",
      "Serve hot, with or without milk according to preference."
    ]
  },
  {
    id: "ke-032",
    name: "Malenge na Nazi (Pumpkin in Coconut Milk)",
    type: "lunch",
    description: "Sweet pumpkin pieces cooked in creamy coconut milk. A simple yet delicious vegetarian dish from coastal Kenya.",
    preparationTime: 15,
    cookingTime: 30,
    servings: 4,
    totalCost: 180,
    calories: 240,
    image: null,
    tags: ["Vegetarian", "Coastal", "Budget-Friendly", "Sweet"],
    ingredients: [
      { name: "Pumpkin", amount: "1 medium, peeled and cut into chunks" },
      { name: "Coconut Milk", amount: "400ml" },
      { name: "Onion", amount: "1 small, finely chopped" },
      { name: "Garlic", amount: "2 cloves, minced" },
      { name: "Cardamom Pods", amount: "4, crushed" },
      { name: "Cinnamon Stick", amount: "1 small" },
      { name: "Brown Sugar", amount: "1 tbsp (optional)" },
      { name: "Salt", amount: "to taste" },
      { name: "Water", amount: "1/2 cup (if needed)" }
    ],
    nutritionFacts: {
      calories: 240,
      protein: 4,
      carbs: 28,
      fat: 14,
      fiber: 6
    },
    region: "Coastal Kenya",
    instructions: [
      "In a large pot, sauté chopped onions until translucent.",
      "Add minced garlic, cardamom pods, and cinnamon stick, cook for 30 seconds until fragrant.",
      "Add pumpkin chunks and stir to coat with the spices.",
      "Pour in coconut milk and a little water if needed to just cover the pumpkin.",
      "Season with salt and brown sugar (if using).",
      "Bring to a simmer, then reduce heat to low, cover, and cook for about 20-25 minutes until the pumpkin is tender but not mushy.",
      "Check seasoning and adjust as needed.",
      "Serve hot as a side dish with rice or chapati, or as a light main course."
    ]
  },
  {
    id: "ke-033",
    name: "Masala Chips (Kenyan Spiced Fries)",
    type: "snack, lunch",
    description: "A popular Kenyan street food - French fries tossed with a spicy tomato sauce. Found at roadside kiosks throughout urban Kenya.",
    preparationTime: 15,
    cookingTime: 20,
    servings: 4,
    totalCost: 200,
    calories: 380,
    image: null,
    tags: ["Street Food", "Spicy", "Urban", "Vegetarian"],
    ingredients: [
      { name: "Potatoes", amount: "1kg, cut into fries" },
      { name: "Vegetable Oil", amount: "for deep frying" },
      { name: "Onion", amount: "1 medium, finely chopped" },
      { name: "Garlic", amount: "2 cloves, minced" },
      { name: "Tomatoes", amount: "2 large, chopped" },
      { name: "Tomato Paste", amount: "2 tbsp" },
      { name: "Chili Powder", amount: "1 tsp (adjust to taste)" },
      { name: "Ground Cumin", amount: "1/2 tsp" },
      { name: "Ground Coriander", amount: "1/2 tsp" },
      { name: "Lemon Juice", amount: "1 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Fresh Cilantro", amount: "handful, chopped" }
    ],
    nutritionFacts: {
      calories: 380,
      protein: 5,
      carbs: 50,
      fat: 18,
      fiber: 5
    },
    region: "Urban Kenya",
    instructions: [
      "Rinse and pat dry the potato fries. Heat oil for deep frying.",
      "Fry the potatoes in batches until golden and crispy. Drain on paper towels and set aside.",
      "In a separate pan, heat 2 tablespoons of oil and sauté onions until golden.",
      "Add minced garlic and cook for 30 seconds until fragrant.",
      "Add chopped tomatoes and tomato paste, cook until tomatoes break down into a sauce.",
      "Add all the spices - chili powder, cumin, and coriander. Stir well.",
      "Season with salt and lemon juice, adjust to taste.",
      "Add the fried potatoes to the sauce and toss gently to coat all fries with the sauce.",
      "Garnish with fresh cilantro and serve hot as a snack or side dish."
    ]
  },
  {
    id: "ke-034",
    name: "Kuku wa Kupaka (Chicken in Coconut Sauce)",
    type: "dinner",
    description: "Grilled chicken smothered in a rich coconut curry sauce. A coastal delicacy that combines African and Arab influences.",
    preparationTime: 30,
    cookingTime: 45,
    servings: 4,
    totalCost: 650,
    calories: 520,
    image: null,
    tags: ["Coastal", "Special Occasion", "Meat", "Spicy"],
    ingredients: [
      { name: "Chicken Pieces", amount: "1kg, bone-in" },
      { name: "Coconut Milk", amount: "500ml" },
      { name: "Onion", amount: "1 large, finely chopped" },
      { name: "Garlic", amount: "4 cloves, minced" },
      { name: "Ginger", amount: "2 tbsp, grated" },
      { name: "Green Chili", amount: "2, slit lengthwise" },
      { name: "Tomatoes", amount: "2 medium, chopped" },
      { name: "Ground Cumin", amount: "1 tsp" },
      { name: "Ground Coriander", amount: "1 tsp" },
      { name: "Turmeric Powder", amount: "1/2 tsp" },
      { name: "Garam Masala", amount: "1/2 tsp" },
      { name: "Vegetable Oil", amount: "3 tbsp" },
      { name: "Lemon Juice", amount: "2 tbsp" },
      { name: "Fresh Cilantro", amount: "handful, chopped" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 520,
      protein: 42,
      carbs: 10,
      fat: 36,
      fiber: 3
    },
    region: "Coastal Kenya",
    instructions: [
      "Marinate chicken pieces with half of the minced garlic, ginger, lemon juice, and salt for at least 30 minutes.",
      "Grill or pan-fry the marinated chicken until golden brown on all sides. Set aside.",
      "In a large pot, heat oil and sauté onions until golden.",
      "Add remaining garlic, ginger, and green chilies. Cook for 1 minute.",
      "Add chopped tomatoes and cook until soft.",
      "Add all the dry spices - cumin, coriander, turmeric, and garam masala. Stir well.",
      "Pour in the coconut milk, bring to a simmer, and cook for 5 minutes.",
      "Add the grilled chicken pieces to the coconut sauce.",
      "Cover and simmer on low heat for about 20 minutes until chicken is fully cooked and tender.",
      "Adjust seasoning if needed and garnish with fresh cilantro.",
      "Serve hot with rice or chapati."
    ]
  },
  {
    id: "ke-035",
    name: "Ndizi Kaanga (Fried Plantains)",
    type: "snack, lunch",
    description: "Sweet ripe plantains fried to golden perfection. A popular street snack or side dish in many parts of Kenya.",
    preparationTime: 5,
    cookingTime: 10,
    servings: 3,
    totalCost: 100,
    calories: 220,
    image: null,
    tags: ["Snack", "Sweet", "Budget-Friendly", "Quick", "Vegetarian"],
    ingredients: [
      { name: "Ripe Plantains", amount: "3 large" },
      { name: "Vegetable Oil", amount: "3 tbsp" },
      { name: "Salt", amount: "a pinch (optional)" },
      { name: "Ground Cinnamon", amount: "1/4 tsp (optional)" },
      { name: "Honey or Maple Syrup", amount: "for drizzling (optional)" }
    ],
    nutritionFacts: {
      calories: 220,
      protein: 1,
      carbs: 48,
      fat: 5,
      fiber: 3
    },
    region: "Nationwide",
    instructions: [
      "Peel the ripe plantains and slice them diagonally into 1/2-inch thick pieces.",
      "Heat oil in a large frying pan over medium heat.",
      "Place plantain slices in the hot oil and fry for 2-3 minutes on each side until golden brown.",
      "Remove with a slotted spoon and drain on paper towels.",
      "Sprinkle with a tiny pinch of salt if desired, or dust with cinnamon for a sweet version.",
      "For extra sweetness, drizzle lightly with honey or maple syrup.",
      "Serve warm as a snack, dessert, or side dish."
    ]
  },
  {
    id: "ke-036",
    name: "Terere (Amaranth Leaves Stew)",
    type: "lunch, dinner", 
    description: "Nutritious indigenous vegetable stew made with amaranth leaves. High in iron, vitamins, and fiber.",
    preparationTime: 15,
    cookingTime: 25,
    servings: 4,
    totalCost: 120,
    calories: 150,
    image: null,
    tags: ["Traditional", "Vegetarian", "Healthy", "Budget-Friendly", "Indigenous"],
    ingredients: [
      { name: "Amaranth Leaves (Terere)", amount: "2 large bunches, chopped" },
      { name: "Onion", amount: "1 medium, chopped" },
      { name: "Tomatoes", amount: "2 medium, chopped" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Water", amount: "1/2 cup" }
    ],
    nutritionFacts: {
      calories: 150,
      protein: 8,
      carbs: 18,
      fat: 7,
      fiber: 7
    },
    region: "Nationwide",
    instructions: [
      "Wash the amaranth leaves thoroughly and drain well.",
      "Heat oil in a large pot and sauté chopped onions until translucent.",
      "Add chopped tomatoes and cook until soft and slightly mushy.",
      "Add the amaranth leaves and stir to combine with the onion-tomato mixture.",
      "Add water, cover the pot, and bring to a simmer.",
      "Cook for about 15-20 minutes until the leaves are tender but still vibrant.",
      "Season with salt to taste.",
      "Serve hot with ugali, chapati, or rice."
    ]
  },
  {
    id: "ke-037",
    name: "Sukuma Wiki na Nyama",
    type: "lunch, dinner",
    description: "Collard greens cooked with beef, a nutritious and hearty meal.",
    preparationTime: 15,
    cookingTime: 30,
    servings: 4,
    totalCost: 300,
    calories: 350,
    image: null,
    tags: ["Traditional", "High Protein", "Budget-Friendly"],
    ingredients: [
      { name: "Beef", amount: "500g" },
      { name: "Sukuma Wiki (Collard Greens)", amount: "1 bunch" },
      { name: "Onion", amount: "1 large" },
      { name: "Tomatoes", amount: "2 medium" },
      { name: "Garlic", amount: "2 cloves" },
      { name: "Cooking Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 350,
      protein: 25,
      carbs: 10,
      fat: 20,
      fiber: 5
    },
    region: "Nationwide",
    instructions: [
      "Cut beef into small pieces and cook in a pot until browned.",
      "Add chopped onions and garlic, sauté until translucent.",
      "Add chopped tomatoes and cook until soft.",
      "Add chopped sukuma wiki and salt, stir well.",
      "Cover and cook for 10-15 minutes until greens are tender.",
      "Serve hot with ugali or rice."
    ]
  },
  {
    id: "ke-038",
    name: "Tilapia Fry",
    type: "lunch, dinner",
    description: "Crispy fried tilapia served with kachumbari and ugali.",
    preparationTime: 20,
    cookingTime: 30,
    servings: 4,
    totalCost: 600,
    calories: 450,
    image: null,
    tags: ["Fish", "Traditional", "High Protein"],
    ingredients: [
      { name: "Tilapia Fish", amount: "4 whole" },
      { name: "Lemon", amount: "1" },
      { name: "Garlic", amount: "4 cloves" },
      { name: "Salt", amount: "to taste" },
      { name: "Vegetable Oil", amount: "for frying" },
      { name: "Kachumbari", amount: "to serve" },
      { name: "Ugali", amount: "to serve" }
    ],
    nutritionFacts: {
      calories: 450,
      protein: 40,
      carbs: 10,
      fat: 25,
      fiber: 2
    },
    region: "Lake Victoria Region",
    instructions: [
      "Clean and score the tilapia fish.",
      "Rub with lemon juice, crushed garlic, and salt.",
      "Heat oil in a frying pan and fry the fish until golden brown and crispy.",
      "Serve hot with kachumbari and ugali."
    ]
  },
  {
    id: "ke-039",
    name: "Matumbo Fry",
    type: "lunch, dinner",
    description: "Fried tripe with onions and tomatoes, a flavorful and hearty dish.",
    preparationTime: 20,
    cookingTime: 60,
    servings: 4,
    totalCost: 350,
    calories: 300,
    image: null,
    tags: ["Traditional", "High Protein", "Budget-Friendly"],
    ingredients: [
      { name: "Tripe", amount: "500g" },
      { name: "Onion", amount: "1 large" },
      { name: "Tomatoes", amount: "2 medium" },
      { name: "Garlic", amount: "3 cloves" },
      { name: "Cooking Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 300,
      protein: 20,
      carbs: 5,
      fat: 20,
      fiber: 2
    },
    region: "Nationwide",
    instructions: [
      "Clean and cut tripe into small pieces.",
      "Boil tripe in water until tender, about 40 minutes.",
      "Drain and set aside.",
      "Heat oil in a pan, add chopped onions and garlic, sauté until translucent.",
      "Add chopped tomatoes and cook until soft.",
      "Add boiled tripe and salt, stir well.",
      "Fry for 10-15 minutes until tripe is crispy.",
      "Serve hot with ugali or rice."
    ]
  },
  {
    id: "ke-040",
    name: "Kuku Paka",
    type: "lunch, dinner",
    description: "Grilled chicken in a rich coconut curry sauce, a coastal delicacy.",
    preparationTime: 30,
    cookingTime: 45,
    servings: 4,
    totalCost: 650,
    calories: 520,
    image: null,
    tags: ["Coastal", "Special Occasion", "Meat", "Spicy"],
    ingredients: [
      { name: "Chicken Pieces", amount: "1kg, bone-in" },
      { name: "Coconut Milk", amount: "500ml" },
      { name: "Onion", amount: "1 large, finely chopped" },
      { name: "Garlic", amount: "4 cloves, minced" },
      { name: "Ginger", amount: "2 tbsp, grated" },
      { name: "Green Chili", amount: "2, slit lengthwise" },
      { name: "Tomatoes", amount: "2 medium, chopped" },
      { name: "Ground Cumin", amount: "1 tsp" },
      { name: "Ground Coriander", amount: "1 tsp" },
      { name: "Turmeric Powder", amount: "1/2 tsp" },
      { name: "Garam Masala", amount: "1/2 tsp" },
      { name: "Vegetable Oil", amount: "3 tbsp" },
      { name: "Lemon Juice", amount: "2 tbsp" },
      { name: "Fresh Cilantro", amount: "handful, chopped" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 520,
      protein: 42,
      carbs: 10,
      fat: 36,
      fiber: 3
    },
    region: "Coastal Kenya",
    instructions: [
      "Marinate chicken pieces with half of the minced garlic, ginger, lemon juice, and salt for at least 30 minutes.",
      "Grill or pan-fry the marinated chicken until golden brown on all sides. Set aside.",
      "In a large pot, heat oil and sauté onions until golden.",
      "Add remaining garlic, ginger, and green chilies. Cook for 1 minute.",
      "Add chopped tomatoes and cook until soft.",
      "Add all the dry spices - cumin, coriander, turmeric, and garam masala. Stir well.",
      "Pour in the coconut milk, bring to a simmer, and cook for 5 minutes.",
      "Add the grilled chicken pieces to the coconut sauce.",
      "Cover and simmer on low heat for about 20 minutes until chicken is fully cooked and tender.",
      "Adjust seasoning if needed and garnish with fresh cilantro.",
      "Serve hot with rice or chapati."
    ]
  },
  {
    id: "ke-041",
    name: "Mokimo",
    type: "lunch, dinner",
    description: "Mashed potatoes with green peas, corn, and pumpkin leaves, a traditional Kikuyu dish.",
    preparationTime: 20,
    cookingTime: 40,
    servings: 6,
    totalCost: 200,
    calories: 250,
    image: null,
    tags: ["Traditional", "Vegetarian", "Budget-Friendly"],
    ingredients: [
      { name: "Potatoes", amount: "1kg" },
      { name: "Green Peas", amount: "200g" },
      { name: "Corn Kernels", amount: "200g" },
      { name: "Pumpkin Leaves", amount: "1 bunch" },
      { name: "Onion", amount: "1 medium" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 250,
      protein: 6,
      carbs: 50,
      fat: 2,
      fiber: 8
    },
    region: "Central Kenya",
    instructions: [
      "Peel and cut potatoes into chunks, then boil until soft.",
      "Cook green peas and corn separately.",
      "Blanch the pumpkin leaves briefly.",
      "Sauté the onions until golden.",
      "Mash the potatoes and mix in all other ingredients.",
      "Season with salt and serve hot."
    ]
  },
  {
    id: "ke-042",
    name: "Kuku Choma",
    type: "lunch, dinner",
    description: "Grilled chicken marinated with spices, a popular Kenyan barbecue dish.",
    preparationTime: 30,
    cookingTime: 45,
    servings: 4,
    totalCost: 600,
    calories: 500,
    image: null,
    tags: ["Traditional", "High Protein", "Special Occasion"],
    ingredients: [
      { name: "Chicken Pieces", amount: "1kg" },
      { name: "Lemon", amount: "1" },
      { name: "Garlic", amount: "4 cloves" },
      { name: "Ginger", amount: "2 tbsp" },
      { name: "Paprika", amount: "1 tsp" },
      { name: "Cumin Powder", amount: "1 tsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Vegetable Oil", amount: "2 tbsp" }
    ],
    nutritionFacts: {
      calories: 500,
      protein: 40,
      carbs: 5,
      fat: 35,
      fiber: 2
    },
    region: "Nationwide",
    instructions: [
      "Marinate chicken pieces with lemon juice, crushed garlic, grated ginger, paprika, cumin powder, salt, and vegetable oil for at least 30 minutes.",
      "Grill the marinated chicken over medium heat until fully cooked and slightly charred.",
      "Serve hot with kachumbari and ugali."
    ]
  },
  {
    id: "ke-043",
    name: "Maharagwe ya Nazi",
    type: "lunch, dinner",
    description: "Red kidney beans cooked in coconut milk, a creamy and flavorful dish.",
    preparationTime: 15,
    cookingTime: 60,
    servings: 6,
    totalCost: 250,
    calories: 300,
    image: null,
    tags: ["Vegetarian", "High Protein", "Budget-Friendly"],
    ingredients: [
      { name: "Red Kidney Beans", amount: "500g, soaked overnight" },
      { name: "Coconut Milk", amount: "400ml" },
      { name: "Tomatoes", amount: "3 medium, chopped" },
      { name: "Onion", amount: "1 large, chopped" },
      { name: "Garlic", amount: "3 cloves, minced" },
      { name: "Green Chilies", amount: "1-2, chopped (optional)" },
      { name: "Ground Cumin", amount: "1 tsp" },
      { name: "Ground Coriander", amount: "1 tsp" },
      { name: "Vegetable Oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
      { name: "Fresh Cilantro/Coriander", amount: "handful, chopped" }
    ],
    nutritionFacts: {
      calories: 300,
      protein: 16,
      carbs: 42,
      fat: 10,
      fiber: 12
    },
    region: "Coastal Kenya",
    instructions: [
      "Drain and rinse the soaked beans, then place in a pot with enough fresh water to cover. Bring to a boil and cook until beans are tender, about 40-50 minutes.",
      "In a separate pan, heat oil and sauté onions until golden brown.",
      "Add garlic and green chilies, sauté for 1 minute until fragrant.",
      "Add chopped tomatoes and cook until soft and oil begins to separate.",
      "Add ground cumin and coriander, stir well.",
      "Add the cooked beans with some of their cooking liquid, coconut milk, and salt.",
      "Simmer on low heat for 15-20 minutes until the stew thickens.",
      "Garnish with fresh cilantro and serve hot with rice, chapati, or ugali."
    ]
  },
  {
    id: "ke-044",
    name: "Kachumbari",
    type: "snack, side",
    description: "Fresh and tangy Kenyan salad made with tomatoes, onions, and cilantro. It's the perfect accompaniment to grilled meats and other main dishes.",
    preparationTime: 10,
    cookingTime: 0,
    servings: 4,
    totalCost: 100,
    calories: 60,
    image: null,
    tags: ["Salad", "Quick", "No-Cook", "Vegetarian"],
    ingredients: [
      { name: "Tomatoes", amount: "3 medium, diced" },
      { name: "Red Onion", amount: "1 medium, finely sliced" },
      { name: "Cilantro/Coriander", amount: "1/4 cup, chopped" },
      { name: "Green Chili", amount: "1 small, finely chopped (optional)" },
      { name: "Lemon or Lime Juice", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" }
    ],
    nutritionFacts: {
      calories: 60,
      protein: 2,
      carbs: 13,
      fat: 0,
      fiber: 3
    },
    region: "Nationwide",
    instructions: [
      "Soak sliced onions in cold water for 5-10 minutes to reduce sharpness, then drain well.",
      "In a bowl, combine diced tomatoes and sliced onions.",
      "Add chopped cilantro and green chili (if using).",
      "Drizzle with lemon or lime juice.",
      "Season with salt and toss gently to combine.",
      "Let the salad sit for about 5 minutes to allow flavors to meld before serving."
    ]
  },
  {
    id: "ke-045",
    name: "Samosas",
    type: "snack, breakfast",
    description: "Popular Kenyan street food with Indian influence - crispy triangular pastries filled with seasoned minced meat or vegetables.",
    preparationTime: 45,
    cookingTime: 20,
    servings: 12,
    totalCost: 350,
    calories: 180,
    image: null,
    tags: ["Snack", "Street Food", "Indian Influence"],
    ingredients: [
      { name: "All-purpose Flour", amount: "2 cups" },
      { name: "Salt", amount: "1 tsp" },
      { name: "Vegetable Oil", amount: "6 tbsp + for frying" },
      { name: "Water", amount: "6-7 tbsp" },
      { name: "Minced Beef or Lamb", amount: "500g" },
      { name: "Onion", amount: "1 large, finely chopped" },
      { name: "Garlic", amount: "3 cloves, minced" },
      { name: "Ginger", amount: "1 tbsp, grated" },
      { name: "Ground Cumin", amount: "1 tsp" },
      { name: "Ground Coriander", amount: "1 tsp" },
      { name: "Garam Masala", amount: "1/2 tsp" },
      { name: "Green Peas", amount: "1/2 cup" },
      { name: "Cilantro/Coriander", amount: "1/4 cup, chopped" }
    ],
    nutritionFacts: {
      calories: 180,
      protein: 8,
      carbs: 15,
      fat: 10,
      fiber: 1
    },
    region: "Urban Kenya",
    instructions: [
      "For the dough: Mix flour and salt in a bowl. Add oil and rub until mixture resembles breadcrumbs. Add water gradually and knead to form a stiff dough. Cover and rest for 30 minutes.",
      "For the filling: Heat oil in a pan, add onions and sauté until golden. Add garlic and ginger, cook for 1 minute.",
      "Add minced meat and brown it. Add all spices and salt, cook until fragrant.",
      "Add green peas and cook until meat is fully cooked. Mix in chopped cilantro and let the filling cool.",
      "Divide dough into 6 equal parts. Roll each into a circle and cut in half.",
      "Form each half into a cone, fill with the meat mixture, seal the edges with water.",
      "Deep fry the samosas in hot oil until golden brown and crispy.",
      "Drain on paper towels and serve hot with ketchup or chutney."
    ]
  }
];

export default kenyanMeals;
